language: php

php:
- "5.4"
- "5.3"

before_script:
- protected/tests/travis/install-dependencies.sh
- protected/tests/travis/mysql-schema.sh
- cd protected/tests/

script: phpunit --configuration travis/phpunit.xml --coverage-text unit/