language: php

php:
- "5.4"
- "5.3"

before_script:
- composer install
- mysql -e "CREATE DATABASE berkuliah_test;"
- mysql -u root berkuliah_test < protected/data/berkuliah.sql
- cd protected/tests/

script: phpunit --configuration travis-phpunit.xml --coverage-text unit/